language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - PYTHONPATH="src"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install ipaddress; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install ipaddress; fi
  - 'pip install pyzmq'
branches:
  only:
    - master
script: 
    - PYTHONPATH="." python tests/test_pyre.py
    - PYTHONPATH="." python tests/test_zbeacon.py
    - PYTHONPATH="." python tests/test_zhelper.py
    - PYTHONPATH="." python tests/test_zactor.py
